UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/core/views.py
from flask import render_template, request, Blueprint
#from webapplication.models import BlogPost
from webapplication import db, app
from webapplication.models import Produs
import time
import socket
# In the first 60 seconds, the app will return 500, to simulate a startup
return500Seconds = 60
startTime = time.time()

def getUptime():
    """
    Returns the number of seconds since the program started.
    """
    # do return startTime if you just want the process start time
    return time.time() - startTime


core = Blueprint('core',__name__)

@core.route('/')
def index():
  produse = db.session.query(Produs).all()
  instance_ip = socket.gethostbyname(socket.gethostname())

  if getUptime() < return500Seconds:
    return '{"appVersion": "1", "status": "500", "instance_ip": "' + instance_ip + '"}'

  return render_template('index.html', produse=produse, instance_ip=instance_ip)

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/useri/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, current_user, logout_user, login_required
from webapplication import db, app
from werkzeug.security import generate_password_hash,check_password_hash
from webapplication.models import User, Produs
from webapplication.useri.forms import RegistrationForm, LoginForm, UpdateUserForm, ForgotForm
import time
import hashlib
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import socket

useri = Blueprint('useri', __name__)


gmail_user = 'SENDER@EMAIL.com'
gmail_password = 'PASSWORD'

def sendMail(email, subject, hash, tip):

  msg = MIMEMultipart('alternative')
  msg['Subject'] = subject
  msg['From'] = gmail_user
  msg['To'] = email

  if tip == "activate":
    body = "<b>Salut " + email.split("@")[0] + "!</b><br>"
    body += "<br><br>Contul a fost creat cu succes, insa necesita activare pentru a putea fi folosit!"
    body += "<br> Pentru a il activa, acceseaza link-ul <a href='http://webapplication.ro/" + email + "/" + hash + "/activate" + "'>urmator</a></b><br><br>"
  elif tip == "forgot":
    body = "<b>Salut " + email.split("@")[0] + "!</b><br>"
    body += "<br><br>Ai solicitat resetarea parolei!"
    body += "<br> Pentru a alege o noua parola, acceseaza link-ul <a href='http://webapplication.ro/" + email + "/" + hash + "/forgot" + "'>urmator</a></b><br><br>"
    body += "<br><br>Daca nu tu ai solicitat resetarea parolei, ignora acest mail, contul tau este in siguranta"

  HTMLpart = MIMEText(body, 'html')
  msg.attach(HTMLpart)

  try:
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.ehlo()
    server.login(gmail_user, gmail_password)
    server.sendmail(gmail_user, email, msg.as_string())
    server.close()

    print('Email sent to ' + email)
  except:
    print('Something went wrong when sending email to ' + email)


@useri.route('/register', methods=['GET', 'POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
    forHash = str(form.email.data).encode('utf-8') + str(time.time()).encode('utf-8')
    hashObj = hashlib.sha1(forHash)
    hashString = str(hashObj.hexdigest())
    user = User(email=form.email.data,
                numeUser=form.numeUser.data,
                prenumeUser=form.prenumeUser.data,
                adresa=form.adresa.data,
                parola=form.parola.data,
                hash=hashString)

    db.session.add(user)
    db.session.commit()
    sendMail(form.email.data, "Activare cont tarabaluieusebiu.ro", hashString, "activate")
    flash('Multumim pentru inregistrare! Pentru a finaliza crearea contului, te rog verifica mailul si acceseaza link-ul de activare')
    return redirect(url_for('useri.login'))
  return render_template('register.html', form=form)


@useri.route('/login', methods=['GET', 'POST'])
def login():
  form = LoginForm()
  if form.validate_on_submit():
    # Grab the user from our User Models table
    user = User.query.filter_by(email = form.email.data).first()

    # Check that the user was supplied and the password is right
    # The verify_password method comes from the User object
    # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

    if user is not None:
      if user.activated is True and user.check_password(form.parola.data):
        #Log in the user
        login_user(user)

        # If a user was trying to visit a page that requires a login
        # flask saves that URL as 'next'.
        next = request.args.get('next')

        # So let's now check if that next exists, otherwise we'll go to
        # the welcome page.
        if next == None or not next[0]=='/':
          next = url_for('useri.userhome', email=user.email)

        return redirect(next)
      else:
        if user.activated is False:
          flash('Contul nu a fost inca activat')
        else:
          flash('Email sau parola gresita!')
    else:
      flash('Email-ul nu este gasit in baza de date!')

  return render_template('login.html', form=form)


@useri.route('/uitatparola', methods=['GET', 'POST'])
def uitatparola():
  form = ForgotForm()
  if form.validate_on_submit():

    # Grab the user from our User Models table
    user = User.query.filter_by(email=form.email.data).first()

    if user is not None:
      sendMail(user.email, "Resetare parola tarabaluieusebiu.ro", user.hash, "forgot")
      flash('Un mail cu link de resetare a parolei a fost trimis la mailul introdus')
    else:
      flash('Nu avem in baza de date acest mail')
  return render_template('uitatparola.html', form=form)

@useri.route('/<email>/<hash>/forgot', methods=['GET', 'POST'])
def resetparola(email, hash):

  # Grab the user from our User Models table
  user = User.query.filter_by(email=email).first()

  if user is not None and hash == user.hash:
    login_user(user)
    flash("Actualizeaza-ti parola!")
    return redirect(url_for('useri.updateuser', email=email))
  else:
    flash("Nu s-a putut reseta parola. Te rugam sa accesezi din nou linkul din email!")
    return redirect(url_for('useri.updateuser', email=email))



@useri.route("/logout")
@login_required
def logout():
  logout_user()
  return redirect(url_for('core.index'))


@useri.route("/<email>/<hash>/activate", methods=['GET', 'POST'])
def activateuser(email, hash):
  form = LoginForm()

  user = User.query.filter_by(email = email).first()
  if user is not None and hash == user.hash:
    user.activated = True
    db.session.commit()
    flash("Felicitari! Contul a fost activat cu success! Te poti autentifica")
    return redirect(url_for('useri.userhome', email=email))
  else:
    flash("Nu s-a putut activa contul. Te rugam sa accesezi din nou linkul din email!")
    return redirect(url_for('useri.userhome', email=email))

@useri.route("/<email>/updateuser", methods=['GET', 'POST'])
@login_required
def updateuser(email):
  if email != current_user.email:
    # Forbidden, No Access
    abort(403)
  form = UpdateUserForm()

  if form.validate_on_submit():

    current_user.email = form.email.data
    current_user.numeUser = form.numeUser.data
    current_user.prenumeUser = form.prenumeUser.data
    current_user.adresa = form.adresa.data
    if form.parola.data:
      current_user.parola=generate_password_hash(form.parola.data)

    db.session.commit()
    flash('Datele contului au fost actualizate cu succes.')
    return redirect(url_for('useri.userhome', email=current_user.email))

  elif request.method == 'GET':
    form.email.data = current_user.email
    form.numeUser.data = current_user.numeUser
    form.prenumeUser.data = current_user.prenumeUser
    form.adresa.data = current_user.adresa

  return render_template('updateuser.html', form=form)


@useri.route("/<email>/removeuser", methods=['GET', 'POST'])
@login_required
def removeuser(email):
  if email != current_user.email:
    # Forbidden, No Access
    abort(403)
  return render_template('removeuser.html', email=email)

@useri.route("/<email>/removeuseryes", methods=['GET', 'POST'])
@login_required
def removeuseryes(email):
  if email != current_user.email:
    # Forbidden, No Access
    abort(403)

  logout_user()

  db.session.delete(user)

  db.session.commit()

  produse = db.session.query(Produs).all()
  instance_ip = socket.gethostbyname(socket.gethostname())

  flash("Ne pare rau ca pleci! Contul tau a fost sters cu scucces")

  return render_template('index.html', produse=produse, instance_ip=instance_ip)



@useri.route("/<email>")
@login_required
def userhome(email):

  if email != current_user.email:
    # Forbidden, No Access
    abort(403)

  user = User.query.filter_by(email=email).first_or_404()

  if current_user.prenumeUser is None or current_user.prenumeUser == "" or current_user.prenumeUser == " ":
    nume = current_user.email.split("@")[0]
  else:
    nume = current_user.prenumeUser

  ### Get produse to render
  produse = getProduseForUser(user.shopping)
  return render_template('userhome.html', user=user, nume=nume, produse=produse)

@login_required
@app.route('/<email>/add', methods=['POST'])
def add_product_to_cart(email):

  ### Basic stuff
  if email != current_user.email:
    # Forbidden, No Access
    abort(403)

  user = User.query.filter_by(email=email).first_or_404()

  if current_user.prenumeUser is None or current_user.prenumeUser == "" or current_user.prenumeUser == " ":
    nume = current_user.email.split("@")[0]
  else:
    nume = current_user.prenumeUser

  ### Add product to user cart
  newCartString = updateProduseForUser(user.shopping, request.form['code'], request.form['quantity'])

  ### Write in DB
  user.shopping = newCartString
  db.session.commit()

  ### Get produse to render
  produse = getProduseForUser(user.shopping)


  return render_template('userhome.html', user=user, nume=nume, produse=produse)


@login_required
@app.route('/<email>/order', methods=['POST'])
def order_products(email):

  ### Basic stuff
  if email != current_user.email:
    # Forbidden, No Access
    abort(403)

  user = User.query.filter_by(email=email).first_or_404()

  if current_user.prenumeUser is None or current_user.prenumeUser == "" or current_user.prenumeUser == " ":
    nume = current_user.email.split("@")[0]
  else:
    nume = current_user.prenumeUser

  ### Get produse to render
  produse = getProduseForUser(user.shopping)
  if len(produse) == 0:
    flash("Cosul este gol. Adauga produse in cos pentru a le putea comanda.")
  else:
    flash("Comanda plasata. Produsele vor fi expediate la adresa specificata in cont.")

  ### Add product to user cart
  newCartString = ""

  ### Write in DB
  user.shopping = newCartString
  db.session.commit()

  ### Get produse to render
  produse = getProduseForUser(user.shopping)

  return render_template('userhome.html', user=user, nume=nume, produse=produse)

@login_required
@app.route('/<email>/goleste', methods=['POST'])
def goleste(email):

  ### Basic stuff

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="/static/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="/static/master.css"/>

    <title>Taraba lui Eusebiu</title>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">
        <img src="/static/mainlogo.png" width="50" height="50" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link mr-3" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li id="menu-item-?????" class="nav-item btn btn-success btn-sm mr-3">
              <a class="nav-link" href="{{ url_for('useri.userhome', email=current_user.email) }}">Contul meu</a>
            </li>
            <li id="menu-item-??????" class="nav-item btn btn-secondary btn-sm mr-3">
              <a class="nav-link" href="{{ url_for('useri.logout') }}">Logout</a>
            </li>
          {% else %}
            <li id="menu-item-?????" class="nav-item btn btn-primary btn-sm mr-3">
              <a class="nav-link" href="/register">Sign Up</a>
            </li>
            <li id="menu-item-??????" class="nav-item btn btn-success btn-sm mr-3">
              <a class="nav-link" href="/login">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <br><br><br>


    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="alert alert-primary alert-dismissible fade show alerta-jos" role="alert">
          {% for message in messages %}
            {{ message }}
            <br>
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endwith %}


    <!-- Here comes all the pages -->
    {% block content %}
    {% endblock %}

    <!--
    <footer class="page-footer font-small blue">

      <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="/"> webapplication.ro</a>
      </div>
    </footer>
    -->

  </body>
</html>

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/index.html
{% extends "base.html" %}
{% block content %}

<link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css" />

<br>
<br>
<div align='center'>
  <h1 >Bine ati venit la magazinul nostru - Versiunea 1 - IP: {{ instance_ip }}. Mai jos gasiti lista de produse!</h1>
</div>

<div class="margini">
  <div class="display-product-items" id="product-grid" align="center">
    {% for product in produse %}
    <div class="product-item">
      <form method="post" action="/{{ current_user.email }}/add">
        <div class="product-image"><img src="/static/{{ product.imagine }}"></div>
        <div class="product-tile-footer">
          <div class="product-title">{{ product.nume }}</div>
          <br>
          <div class="product-price">{{ product.pret }} lei</div>
          <div class="cart-action">
            <input type="hidden" name="code" value="{{ product.cod }}"/>
            <input type="text" class="product-quantity" name="quantity" value="1" size="2" />
            {% if current_user.is_authenticated %}
            <input type="submit" value="Adauga in cos" class="btn btn-primary" />
            {% else %}
            <input value="Log in pentru adaugare" class="btn btn-secondary" disabled />
            {% endif %}
          </div>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

<!--&lt;!&ndash;div pentru generare de card-uri&ndash;&gt;-->
<!--<div align="center" id="product-grid-deprec">-->
<!--  {% for product in produse %}-->
<!--  <div class="product-item">-->
<!--    <form method="post" action="/{{ current_user.email }}/add">-->
<!--      <div class="product-image"><img src="/static/{{ product.imagine }}"></div>-->
<!--      <div class="product-tile-footer">-->
<!--        <div class="product-title">{{ product.nume }}</div>-->
<!--        <br>-->
<!--        <div class="product-price">{{ product.pret }} lei</div>-->
<!--        <div class="cart-action">-->
<!--          <input type="hidden" name="code" value="{{ product.cod }}"/>-->
<!--          <input type="text" class="product-quantity" name="quantity" value="1" size="2" />-->
<!--          {% if current_user.is_authenticated %}-->
<!--            <input type="submit" value="Adauga in cos" class="btn btn-primary" />-->
<!--          {% else %}-->
<!--            <input value="Log in pentru adaugare" class="btn btn-secondary" disabled />-->
<!--          {% endif %}-->
<!--        </div>-->
<!--      </div>-->
<!--    </form>-->
<!--  </div>-->
<!--  {% endfor %}-->
<!--</div>-->

{% endblock %}

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/login.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" type="text/css" href="/static/login.css"/>
<!--Fontawesome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<form method="POST">
  {% if form.email.errors or form.parola.errors%}
    <div class="alert alert-danger" role="alert">
  {% endif %}
  {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
          <br>
        {% endfor %}

  {% endif %}

  {% if form.parola.errors %}
        {% for error in form.parola.errors %}
        {{ error }}
        <br>
        {% endfor %}
  {% endif %}
  {% if form.email.errors or form.parola.errors%}
    </div>
  {% endif %}
</form>

<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card">
      <div class="card-header">
        <h3>Sign In</h3>
      </div>
      <div class="card-body card-body-custom">
        <form method="POST">
          {{ form.hidden_tag() }}
          {{ form.csrf_token }}
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            {{ form.email(class_="form-control") }}
          </div>
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            {{ form.parola(class_="form-control") }}
          </div>



          <div class="form-group">
            {{ form.submit(class_="btn float-right login_btn") }}
          </div>

        </form>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-center links">
          Nu ai cont?<a href="/register">Creeaza cont nou</a>
        </div>
        <div class="d-flex justify-content-center links">
          <a href="/uitatparola">Ai uitat parola?</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!--
<div class="container jumbotron bg-transparent">
  <form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.parola.label }} {{ form.parola() }}
    {{ form.submit() }}
  </form>
</div>
-->

{% endblock %}

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/removeuser.html
{% extends "base.html" %}
{% block content %}


<div class="container jumbotron bg-transparent">
  <h1 class="display-5">Esti sigur ca vrei sa iti stergi definitiv contul?</h1>
    <div class="text-center">
      <a class="btn float-left btn-primary" href="{{ url_for('useri.updateuser', email=current_user.email) }}">Inapoi</a>
      <a class="btn btn-success btn-lg" href="{{ url_for('useri.removeuseryes', email=current_user.email) }}" role="button">Da</a>
      <a class="btn btn-danger btn-lg" href="{{ url_for('useri.userhome', email=current_user.email) }}" role="button">Nu</a>
    </div>
</div>


{% endblock %}

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/uitatparola.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" type="text/css" href="/static/uitatparola.css"/>
<!--Fontawesome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<form method="POST">
  {% if form.email.errors%}
    <div class="alert alert-danger" role="alert">
  {% endif %}
  {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
          <br>
        {% endfor %}

  {% endif %}
  {% if form.email.errors%}
    </div>
  {% endif %}
</form>

<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card">
      <div class="card-header">
        <h3>Introduceti mailul</h3>
      </div>
      <div class="card-body card-body-custom">
        <form method="POST">
          {{ form.hidden_tag() }}
          {{ form.csrf_token }}
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            {{ form.email(class_="form-control") }}
          </div>
          <div class="form-group">
            {{ form.submit(class_="btn float-right login_btn") }}
          </div>

        </form>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-center links">
          Nu ai cont?<a href="/register">Creeaza cont nou</a>
        </div>
        <div class="d-flex justify-content-center links">
          Ai deja cont?<a href="/login">Conecteaza-te</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

UpgradeMethodsProofOfConcept/DockerImages/Web-Version1/webapplication/templates/updateuser.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" type="text/css" href="/static/updateuser.css"/>
<!--Fontawesome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<form method="POST">
  {% if form.email.errors or form.parola.errors or form.parolaConfirm.errors or form.numeUser.errors or form.prenumeUser.errors or form.adresa.errors%}
    <div class="alert alert-danger" role="alert">
  {% endif %}
  {% if form.email.errors %}
    {% for error in form.email.errors %}
      {{ error }}
      <br>
    {% endfor %}

  {% endif %}

  {% if form.parola.errors %}
    {% for error in form.parola.errors %}
    {{ error }}
    <br>
    {% endfor %}
  {% endif %}

  {% if form.parolaConfirm.errors %}
    {% for error in form.parolaConfirm.errors %}
    {{ error }}
    <br>
    {% endfor %}
  {% endif %}

  {% if form.numeUser.errors %}
    {% for error in form.numeUser.errors %}
    {{ error }}
    <br>
    {% endfor %}
  {% endif %}

  {% if form.prenumeUser.errors %}
    {% for error in form.prenumeUser.errors %}
    {{ error }}
    <br>
    {% endfor %}
  {% endif %}

  {% if form.adresa.errors %}
    {% for error in form.adresa.errors %}
    {{ error }}
    <br>
    {% endfor %}
  {% endif %}

  {% if form.email.errors or form.parola.errors or form.parolaConfirm.errors or form.numeUser.errors or form.prenumeUser.errors or form.adresa.errors%}
    </div>
  {% endif %}
</form>

<br><br>
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="card">
      <div class="card-header">
        <h3>Editare cont</h3>
      </div>
      <div class="card-body card-body-custom">
        <form method="POST" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          {{ form.csrf_token }}
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            {{ form.email(class_="form-control") }}
          </div>

          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-id-card"></i></span>
            </div>
            {{ form.numeUser(class_="form-control") }}
          </div>

          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-id-card"></i></span>
            </div>
            {{ form.prenumeUser(class_="form-control") }}
          </div>

          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-building"></i></span>
            </div>
            {{ form.adresa(class_="form-control") }}
          </div>

          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            {{ form.parola(class_="form-control") }}
          </div>

          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            {{ form.parolaConfirm(class_="form-control") }}
          </div>

          <div class="form-group">
            {{ form.submit(class_="btn float-right login_btn") }}
          </div>
          <a class="btn float-left btn-primary" href="{{ url_for('useri.userhome', email=current_user.email)}}">Inapoi</a>

        </form>
    </div>
  </div>
</div>
<br><br>
<div align='center'>
  <a class="btn btn-danger" href="{{ url_for('useri.removeuser', email=current_user.email)}}" role="button">Stergere Cont</a>
</div>
<br><br>
{% endblock content %}